name: xnz_image
description: A Flutter component package with a demo app for network image loading and caching-ready UI behavior.
version: 0.1.4
homepage: https://github.com/qqxnz/xnz_image.git
repository: https://github.com/qqxnz/xnz_image.git
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  xnz_image_core:
    path: packages/xnz_image_core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
