name: xnz_image_svg
description: SVG support extension for xnz_image.
version: 0.1.8
homepage: https://github.com/qqxnz/xnz_image.git
repository: https://github.com/qqxnz/xnz_image.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  xnz_image: ^0.1.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
